services:
  orders-service:
    build: ./orders-service
    ports:
      - "3000:3000"
    environment:
      INVENTORY_URL: http://inventory-service:3001
      PAYMENTS_URL: http://payments-service:3002
      REDIS_HOST: redis
      DATABASE_HOST: database-1.cj6tlznf25rb.us-east-1.rds.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_USER: SOAprojectOrder
      DATABASE_PASS: Project#SOA#37900
      DATABASE_NAME: postgres
      JWT_SECRET: supersecret
    depends_on:
      - redis
      - inventory-service
      - payments-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "3001:3001"
    environment:
      REDIS_HOST: redis
      DATABASE_HOST: database-2.cj6tlznf25rb.us-east-1.rds.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_USER: SOAprojectOrder
      DATABASE_PASS: Project#SOA#37900
      DATABASE_NAME: postgres
    depends_on:
      - redis

  payments-service:
    build: ./payments-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_HOST: database-3-soa.cj6tlznf25rb.us-east-1.rds.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_USER: SOAprojectOrder
      DATABASE_PASS: Project#SOA#37900
      DATABASE_NAME: postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"
